tender/urls.py
# -*- coding: utf-8 -*-
import os
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings 

urlpatterns = patterns('',
    url(r'^show/(?P<tender_id>\d+)/$', 'tender.views.show_tender', name="show_tender"),    
    # url(r'^add/$', 'tender.views.add_tender', name='add_tender'),
    url(r'^all/$', 'tender.views.all_tenders', name='all_tenders'),
    url(r'^my/$', 'tender.views.my_tenders', name='my_tenders'),
    url(r'^company/$', 'tender.views.company_tenders', name='company_tenders'),
    url(r'^stop_tender/$', 'tender.views.stop_tender', name="stop_tender"),
    url(r'^final_tender/$', 'tender.views.final_tender', name="final_tender"),
    url(r'^send_contacts/$', 'tender.views.send_contacts', name="send_contacts")
)

tender/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.utils.translation import ugettext as _
from accounts.models import *
from tender.models import *
from django_geoip.models import City

class Tender(models.Model):
    TENDER_TYPE = (
        ('dontknow', u'Не уверен'),
        ('production', u'Изготовление'),
        ('sale', u'Продажа'),
    )
    ACTIVITY = (
        ('dontknow', u'Не уверен'),
        ('plastic', u'Пластик'),
        ('polygraphy', u'Полиграфия'),        
    )
    DURATION = (
        ('3', u'срочный - 3 дня'),
        ('7', u'нормальный - 7 дней'),
        ('15', u'долгий - 15 дней'),
    )
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    user = models.ForeignKey(User,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Заказчик')
    # title = models.CharField(max_length=250,
    #                         blank=True, 
    #                         verbose_name=u'Название')
    # tender_type = models.CharField(choices=TENDER_TYPE, 
    #                         max_length=100,
    #                         blank=False,
    #                         # default=u'dontknow',
    #                         verbose_name=u'Тип тендера')
    # activity = models.CharField(choices=ACTIVITY, 
    #                         max_length=100,
    #                         blank=False,
    #                         # default=u'dontknow',
    #                         verbose_name=u'Направление тендера')
    #имеется в ввиду - закрыты участники тендера
    closed = models.BooleanField(default=True, 
                                    verbose_name=u'Тендер закрыт')    
    comment = models.TextField(blank=False, 
                                verbose_name=u'Комментарий')
    city = models.ForeignKey(City,
                            unique=False,
                            blank=True, 
                            null=True,
                            verbose_name=u'Город')
    duration = models.CharField(choices=DURATION, 
                                max_length=3,
                                blank=False,
                                # default='7',
                                verbose_name=u'Длительность тендера')
    datetime_finish = models.DateTimeField(blank=True,
                                        null=True, 
                                        default=None,
                                        verbose_name=u'Дата завершения тендера')    

    def __unicode__(self):
        return u'%s от %s' % (self.comment[:50]+'...', self.user.id)

    def save(self, *args, **kwargs):
        if not self.pk:
            new = True
        else:
            new = False
        super(Tender, self).save(*args, **kwargs)    

        if new:
            ts = TenderState(user=self.user, tender=self, state=u'new')
            ts.save()

class TenderState(models.Model):
    """Состояние тендера
    new - совсем новый,
    open - есть участники,
    work - заказчик посылал запросы участникам,
    tclose - закрыт по времени,
    uclose - закрыт заказчиком,
    final - финализирован заказчиком,
    nottaken - не принят участником,
    taken - принят участником
    """
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    user = models.ForeignKey(User,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Кто поменял')
    tender = models.ForeignKey(Tender,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Тендер')        
    state = models.CharField(max_length=250,
                            blank=False, 
                            verbose_name=u'Состояние')

    def __unicode__(self):
        return u'%s - %s' % (self.state, self.tender.comment[:50]+'...')

class TenderParty(models.Model):
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    user = models.ForeignKey(User,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Исполнитель')
    tender = models.ForeignKey(Tender,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Тендер')        
    comment = models.TextField(blank=True, 
                                verbose_name=u'Комментарий')

    def __unicode__(self):
        return u'%s - %s' % (self.tender.comment[:50]+'...', self.user.my_profile.company.c_title)

    def save(self, *args, **kwargs):
        super(TenderParty, self).save(*args, **kwargs)    

        ts = TenderState(user=self.user, tender=self.tender, state=u'open')
        ts.save()


class TenderPartySend(models.Model):
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    tender_party = models.ForeignKey(TenderParty,
                                    blank=False,
                                    null=False,
                                    verbose_name=u'Участник')
    user = models.ForeignKey(User,
                            blank=False, 
                            null=False, 
                            verbose_name=u'Пославший')

    def __unicode__(self):
        return u'%s - %s' % (self.datetime_add, self.tender_party)

    def save(self, *args, **kwargs):
        super(TenderPartySend, self).save(*args, **kwargs)    

        ts = TenderState(user=self.user, tender=self.tender_party.tender, state=u'work')
        ts.save()        

class TenderFinalComment(models.Model):
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    user = models.ForeignKey(User,
                            blank=False, 
                            null=False, 
                            verbose_name=u'Написал')
    company = models.ForeignKey(Company,
                                unique=False,
                                blank=True, 
                                null=True,
                                verbose_name=u'Компания')
    tender = models.ForeignKey(Tender,
                                blank=False, 
                                null=False, 
                                verbose_name=u'Тендер')        
    comment = models.TextField(blank=True, 
                                verbose_name=u'Комментарий')
    level = models.IntegerField(blank=False,
                                null=False,
                                default=0,
                                verbose_name=u'Уровень 0/1')
    taken = models.BooleanField(default=False,                                     
                                    verbose_name=u'Принят')
    parent = models.ForeignKey('TenderFinalComment',
                                unique=False,
                                blank=True, 
                                null=True,
                                default='Null',
                                verbose_name=u'Родитель')
    rating = models.IntegerField(blank=True,
                                null=True,
                                default=0,
                                verbose_name=u'Рейтинг')

    def __unicode__(self):
        return u'%s - %s' % (self.datetime_add, self.comment[:50]+'...')

    def save(self, *args, **kwargs):
        super(TenderFinalComment, self).save(*args, **kwargs)    

        state = u'final'
        if self.level == 0:
            state = u'final'
        else:
            if self.taken == False:
                state = u'nottaken'
            else:
                state = u'taken'            

        ts = TenderState(user=self.user, tender=self.tender, state=state)
        ts.save()        

class TenderFinalSend(models.Model):
    """Запросы на подтверждение участия"""
    datetime_add = models.DateTimeField(auto_now_add=True, 
                                        default=datetime.datetime.now, 
                                        verbose_name=u'Дата внесения в базу')    
    tender_party = models.ForeignKey(TenderParty,
                                    blank=False,
                                    null=False,
                                    verbose_name=u'Участник')
    user = models.ForeignKey(User,
                            blank=False, 
                            null=False, 
                            verbose_name=u'Пославший')

    def __unicode__(self):
        return u'%s - %s' % (self.datetime_add, self.tender_party)

tender/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from accounts.models import *
from tender.models import *
from accounts.forms import *

class CheckMailForm(forms.Form):
    email = forms.EmailField(required=True)

class NewTenderForm(forms.Form):
    TENDER_TYPE = (
        ('dontknow', u'Не уверен'),
        ('production', u'Изготовление'),
        ('sale', u'Продажа'),
    )
    ACTIVITY = (
        ('dontknow', u'Не уверен'),
        ('plastic', u'Пластик'),
        ('polygraphy', u'Полиграфия'),        
    )
    DURATION = (
        ('3', u'срочный - 3 дня'),
        ('7', u'нормальный - 7 дней'),
        ('15', u'долгий - 15 дней'),
    )

    name = forms.CharField(label=u'Представьтесь *', 
            widget=forms.TextInput(
                attrs={"placeholder": u'Иванов Иван Иванович', 'required': 'required'}
            ),
            required=True
        )
    email = forms.EmailField(label=u'E-mail *',
            widget=forms.TextInput(
                attrs={"placeholder": u'ivanov.ivan@mail.ru', 'required': 'required'}
            ),
            required=True
        )
    phone = forms.CharField(label=u'Телефон',
            widget=forms.TextInput(
                attrs={"placeholder": u'+79267777777', }
            ),
            required=False
        )
    city_select = forms.CharField(label=u'Город *',
            widget=forms.TextInput(
                attrs={'required': 'required', 'data-provide': 'typeahead', 'class': 'typeahead full-width', 'autocomplete': 'off' }
            ),
            required=True
        )
    city = forms.CharField(label=u'Id города',
            widget=forms.HiddenInput(),
            required=True
        )        
    # title = forms.CharField(label=u'Название тендера',
    #         widget=forms.TextInput(
    #             attrs={"class": u'full-width', 'required': 'required'}
    #         ),
    #         required=False
    #     )
    # tender_type = forms.CharField(label=u'Тип тендера',
    #                         widget=forms.Select(choices=TENDER_TYPE),                      
    #                         required=True
    #     )
    # activity = forms.CharField(label=u'Направление',
    #                         # widget=forms.Select(choices=ACTIVITY), 
    #                         widget=forms.HiddenInput(),
    #                         required=True
    #     )
    duration = forms.CharField(label=u'Длительность тендера',
                            widget=forms.Select(choices=DURATION),
                            required=True,
                            initial='7'
        )
    # closed = forms.BooleanField(label=u'Закрытый тендер',
    #         widget=forms.CheckboxInput(attrs={"checked": "checked"}),
    #         initial=True,
    #         required=False,
    #     )   
    comment = forms.CharField(label=u'Описание тендера *',
            widget=forms.Textarea(
                attrs={"rows": 4, "class": u'full-width',}
            ),
            required=True
        )        

    def __init__(self, user=None, *args, **kwargs):
        super(NewTenderForm, self).__init__(*args, **kwargs)
        self._user = user

    def clean(self):
        cleaned_data = super(NewTenderForm, self).clean()
        email = cleaned_data.get('email')

        if not self._user.is_authenticated or not self._user.is_active:
            try:
                mail_in_base = User.objects.get(email=email)
            except:
                pass
            else:
                msg = u"Кто-то с такой почтой уже есть в базе, если это вы - залогиньтесь, пожалуйста.Или же укажите другую почту."
                self._errors["email"] = self.error_class([msg])
                raise forms.ValidationError("Кто-то с такой почтой уже есть в базе, если это вы - залогиньтесь, пожалуйста. Или же укажите другую почту.")

        return cleaned_data

class SaveTenderForm(forms.ModelForm):
    class Meta:
        model = Tender        
        exclude = ['datetime_add', ]
        
class TenderPartyForm(forms.Form):
    comment = forms.CharField(label=u'Комментарии',
            widget=forms.Textarea(
                attrs={"rows": 2, "class": u'full-width',}
            ),
            required=False
        )        

class FilterAllTendersForm(forms.Form):
    TENDER_TYPE = (
        ('all', u'Все'),
        ('production', u'Изготовление'),
        ('sale', u'Продажа'),
    )
    ACTIVITY = (
        ('all', u'Все'),
        ('plastic', u'Пластик'),
        ('polygraphy', u'Полиграфия'),        
    )

    # tender_type = forms.ChoiceField(label=u'Тип тендера',
    #                         widget=forms.RadioSelect(),
    #                         choices=TENDER_TYPE, 
    #                         initial='all',              
    #                         required=False
    #     )
    # activity = forms.ChoiceField(label=u'Направление',
    #                         widget=forms.RadioSelect(), 
    #                         choices=ACTIVITY,
    #                         initial='all',              
    #                         required=False
    #     )
    city_id = forms.CharField(widget=forms.HiddenInput(),
            required=False
        )        
    page = forms.CharField(widget=forms.HiddenInput(),
            required=False
        )        
    sort = forms.CharField(widget=forms.HiddenInput(),
            required=False
        )        

class FinalModalForm(forms.Form):
    tender = forms.IntegerField(required=True)
    rating = forms.IntegerField(required=True)
    company = forms.IntegerField(required=True)
    comment = forms.CharField(label=u'Комментарии',
            widget=forms.Textarea(
                attrs={"rows": 2, "class": u'full-width',}
            ),
            required=False
        )

class FinalChildCommentForm(forms.Form):
    taken = forms.IntegerField(required=True)
    comment_type = forms.CharField(required=True)
    comment = forms.CharField(label=u'Комментарии',
            widget=forms.Textarea(
                attrs={"rows": 2, "class": u'full-width',}
            ),
            required=False
        )

templates/add_tender.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post" class="form-horizontal span9" id="new-tender-form">
        <legend>Новый тендер</legend>
{% csrf_token %}
{% spaceless %}
{{ form.non_field_errors }}
<div class="control-group{% if tender_form.name.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.name.auto_id }}">{{ tender_form.name.label }}</label>
    <div class="controls">
        {{ tender_form.name }} 
        <span class="help-inline">
        {% if tender_form.name.errors %}
            {% for error in tender_form.name.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if tender_form.email.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.email.auto_id }}">{{ tender_form.email.label }}</label>
    <div class="controls">
        {{ tender_form.email }}
        <span class="help-inline">
        {% if tender_form.email.errors %}
            {% for error in tender_form.email.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if tender_form.phone.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.phone.auto_id }}">{{ tender_form.phone.label }}</label>
    <div class="controls">
        {{ tender_form.phone }}
        <span class="help-inline">
        {% if tender_form.phone.errors %}
            {% for error in tender_form.phone.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if tender_form.city_select.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.city_select.auto_id }}">{{ tender_form.city_select.label }}</label>
    <div class="controls">
        {{ tender_form.city_select }}
        {% if tender_form.city_select.errors %}
        <span class="help-inline">
            {% for error in tender_form.city_select.errors %}
            {{ error }}
            {% endfor %}
        </span>
        {% endif %}
        {{ tender_form.city }}
    </div>
    {% if example_citys|length > 0 %}
    <div class="controls" id="your_citys">Например:
        {% for key, value in example_citys.items %}{% spaceless %}
            <a href="#" id="example_city_{{ key }}" data-long="{{ value.1 }}">{{ value.0 }}</a>{% if not forloop.last %},&nbsp;{% endif %}
        {% endspaceless %}{% endfor %}
    </div> 
    {% endif %}
</div>
<div class="control-group{% if tender_form.title.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.title.auto_id }}">{{ tender_form.title.label }}</label>
    <div class="controls">
        {{ tender_form.title }}
        <span class="help-inline">
        {% if tender_form.title.errors %}
            {% for error in tender_form.title.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if tender_form.comment.errors %} error{% endif%}">
    <label class="control-label" for="{{ tender_form.comment.auto_id }}">{{ tender_form.comment.label }}</label>
    <div class="controls">
        {{ tender_form.comment }}
        <span class="help-inline">
        {% if tender_form.comment.errors %}
            {% for error in tender_form.comment.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
{% endspaceless %}
        <div class="controls">
        <button type="submit" class="btn btn-primary full-width"><i class="icon-thumbs-up icon-white"></i> Добавить</button>
        </div>
</form>

<div class="modal hide fade" tabindex="-1" role="dialog" id="pass-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Войти</h3>
  </div>
  <div class="modal-body">
    <form id="modal-login-form">
        <label class="control-label" for="{{ sign_in_form.identification.auto_id }}">{{ sign_in_form.identification.label }}</label>
          {{ sign_in_form.identification }}
        <label class="control-label" for="{{ sign_in_form.password.auto_id }}">{{ sign_in_form.password.label }}</label>
        {{ sign_in_form.password }}
        <a href="{% url userena_password_reset %}" target="blank">Забыл пароль :(</a>
    </form>    
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Закрыть</button>
    <button class="btn btn-primary" id="modal-login-form-submit">Войти</button>
  </div></div>

<script>
$(document).ready(function(){
    $('#id_city_select').typeahead({
        source: function(query, process){
            objects = [];
            map = {};
            $.get("{% url get_citys %}", {query: query}, function(data){
                jdata = data;
            });
            $.each(jdata, function(i, object) {
                map[object.nname] = object;
                objects.push(object.nname);
            });       
            process(objects);     
        },
        updater: function(item) {
            $('#id_city').val(map[item].id);
            return item;
        }        
    });

    $(document).on('blur', '#id_email:not(.uneditable-input)', function(){
        $.post("{% url check_mail %}", 
            {
                email: $('#id_email').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            function(data){
                if (data.success == 3){
                    if ($('div#pass-quest').length<=0){
                        $('#id_email').parent().parent().after('<div class="control-group" id="pass-quest"><div class="controls">Такая почта уже есть. Это вы?<button href="{% url userena_signin %}" id="pass-quest-yes" data-target="pass-modal" class="btn btn-mini btn-success"><i class="icon-user icon-white"></i> Да! Введу пароль</button>  <button id="pass-quest-no" class="btn btn-mini btn-warning"><i class="icon-repeat icon-white"></i> Неа :( Введу другую почту</button></div></div>');                
                    }
                } else if (data.success == 2 && $('div#pass-quest').length>0) {
                    $('#pass-quest').hide('fast', function() { 
                        $(this).remove(); 
                    });                    
                }
            }
        );
    });

    $(document).on('click', '#pass-quest-yes', function(e){
        $('#id_identification').val($('#id_email').val());
        $('#pass-modal').modal('show');
        $('#pass-quest').hide('slow', function() { 
            $(this).remove(); 
        });
        e.preventDefault();                
    });
    
    $(document).on('click', '#pass-quest-no', function(e){
        $('#id_email').val('');
        $('#pass-quest').hide('slow', function() { 
            $(this).remove(); 
        });
        $('#id_email').focus();
        e.preventDefault();                
    });

    $('#modal-login-form-submit').on('click', function(e){
        $('#modal-login-form').submit();
        e.preventDefault();                
    });

    $('#modal-login-form').on('submit', function(e){
        $.ajax({
            url: '{% url ajax_login %}',
            type: 'POST',
            data: {
                csrfmiddlewaretoken: '{{csrf_token}}',
                identification: $('#id_identification').val(),
                password: $('#id_password').val()
            },
        }).done(function(data){
            if(data.success == 1) {
                // console.log(data);
                if(data.user.name != null && data.user.name != 'undefined'){
                    $('#id_name').val(data.user.name);
                    $('#id_name').addClass('uneditable-input').attr('readonly', 'readonly');
                }
                if(data.user.email != null){
                    $('#id_email').val(data.user.email);
                    $('#id_email').addClass('uneditable-input').attr('readonly', 'readonly');
                }
                if(data.user.phone != null && data.user.phone != 'undefined'){
                    $('#id_phone').val(data.user.phone);
                    $('#id_phone').addClass('uneditable-input').attr('readonly', 'readonly');
                }
                if(data.user.city_select != null){
                    $('#id_city_select').val(data.user.city_select);
                }
                if(data.user.city != null){
                    $('#id_city').val(data.user.city);
                }
                $('#pass-modal').modal('hide');   
            }
        });
        e.preventDefault();
    });

    $('div#your_citys a').click(function(e) {
        citya = $(this);
        citylongname = citya.attr('data-long');
        cityid = citya.attr('id').split('_')[2];

        $('#id_city').val(cityid);
        $('#id_city_select').val(citylongname);
        e.preventDefault();
    });
});
</script>
{% endblock %}

templates/feedback_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div id="center-reg-div">    
<form action="" method="post" id="feedback-form">
    <legend>Сообщение</legend>
{% if success == 'thanks' %}
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Спасибо!</strong> Мы всё прочитаем и ответим вам!
</div>
{% endif %}

{% csrf_token %}
{% spaceless %}

{{ form.errors }}

{% for field in form %}
<label for="{{ field.auto_id }}">{{ field.label }}</label>
        {{ field }} 
    <span class="help-inline">
    {% if field.errors %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}
    {% endif %}
    </span>
{% endfor %}
    <div>
    <button type="submit" class="btn btn-primary"><i class="icon-thumbs-up icon-white"></i> Послать</button>
    <p class="pull-right">Или просто <a href="mailto:tender@tenderokon.ru"><i class="icon-envelope"></i>напишите на почту</a></div></p>
</form>
</div>
{% endspaceless %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div id="center-reg-div">    
<form action="" method="post" class="form-horizontal" id="new-reg-form">
    <legend>Регистрация</legend>
{% csrf_token %}
{% spaceless %}

{{ form.errors }}

<div class="control-group{% if form.name.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
    <div class="controls">
        {{ form.name }} 
        <span class="help-inline">
        {% if form.name.errors %}
            {% for error in form.name.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if form.email.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.email.auto_id }}">{{ form.email.label }}</label>
    <div class="controls">
        {{ form.email }} 
        <span class="help-inline">
        {% if form.email.errors %}
            {% for error in form.email.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if form.password1.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.password1.auto_id }}">{{ form.password1.label }}</label>
    <div class="controls">
        {{ form.password1 }} 
        <span class="help-inline">
        {% if form.password1.errors %}
            {% for error in form.password1.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if form.password2.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.password2.auto_id }}">{{ form.password2.label }}</label>
    <div class="controls">
        {{ form.password2 }} 
        <span class="help-inline">
        {% if form.password2.errors %}
            {% for error in form.password2.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if form.phone.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.phone.auto_id }}">{{ form.phone.label }}</label>
    <div class="controls">
        {{ form.phone }}
        <span class="help-inline">
        {% if form.phone.errors %}
            {% for error in form.phone.errors %}
            {{ error }}
            {% endfor %}
        {% endif %}
        </span>
    </div>
</div>
<div class="control-group{% if form.city_select.errors %} error{% endif%}">
    <label class="control-label" for="{{ form.city_select.auto_id }}">{{ form.city_select.label }}</label>
    <div class="controls">
        <input type="text" name="{{ form.city_select.html_name }}" id="{{ form.city_select.auto_id }}" value="{{init_city_name}}" required="required" data-provide="typeahead" class="typeahead input-xlarge" autocomplete="off">
        {% if form.city_select.errors %}
        <span class="help-inline">
            {% for error in form.city_select.errors %}
            {{ error }}
            {% endfor %}
        </span>
        {% endif %}
        <input type="hidden" name="{{ form.city.html_name }}" id="{{ form.city.auto_id }}" value="{{ init_city_id }}">
        {{ form.role }}
        {{ form.master }}
    </div>
    {% if example_citys|length > 0 %}
    <div class="controls" id="your_citys">Например:
        {% for key, value in example_citys.items %}{% spaceless %}
            <a href="#" id="example_city_{{ key }}" data-long="{{ value.1 }}">{{ value.0 }}</a>{% if not forloop.last %},&nbsp;{% endif %}
        {% endspaceless %}{% endfor %}
    </div> 
    {% endif %}
</div>
        <div class="controls">
        <button type="submit" class="btn btn-primary"><i class="icon-thumbs-up icon-white"></i> Регистрация</button>
        </div>
</form>
</div>
{% endspaceless %}

<script>
$(document).ready(function(){
    $('#id_city_select').typeahead({
        source: function(query, process){
            objects = [];
            map = {};
            $.get("{% url get_citys %}", {query: query}, function(data){
                jdata = data;
            });
            $.each(jdata, function(i, object) {
                map[object.nname] = object;
                objects.push(object.nname);
            });       
            process(objects);     
        },
        updater: function(item) {
            $('#id_city').val(map[item].id);
            return item;
        }        
    });

    $('div#your_citys a').click(function(e) {
        citya = $(this);
        citylongname = citya.attr('data-long');
        cityid = citya.attr('id').split('_')[2];

        $('#id_city').val(cityid);
        $('#id_city_select').val(citylongname);
        e.preventDefault();
    });

});
</script>
{% endblock %}